### ISSUE TITLE
Add WebSocket support

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#12]
This will allow features such as real-time admin dashboards, which should offer a responsive user experience.

**Comment by maniksurtani** [comment]
Jetty [supports HTTP/2](https://github.com/fstab/http2-examples/blob/master/jetty-http2-server-example/src/main/java/de/consol/labs/h2c/examples/server/Http2Server.java). We should just enable that by default rather than add support for Websockets. For the purposes of admin dashboards, HTTP/2 streaming will work just as well. And I expect HTTP/2 support to grow over time as Websockets falls out of favour.

**Comment by swankjesse** [comment]
We have Web Socket support.
