### ISSUE TITLE
Adapter to optionally emit logs to StackDriver

### ISSUE THREAD

**Issue by maniksurtani** [square/misk#9]
Should have the ability to emit logs to StackDriver - see https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-java

**Comment by JGulbronson** [comment]
@maniksurtani since we ship with the slf4j api, do we want to use the client library or just get end-users to use the Logback appender (and by extension Logback) https://cloud.google.com/logging/docs/setup/java#logback_appender

That seems less invasive, and requires no changes on Misk's end as far as I can tell.

**Comment by maniksurtani** [comment]
Yes, using the logback appender does seem like the more sensible path here.

**Comment by JGulbronson** [comment]
Sounds good, as far as I can tell there's no other action required on our end. Will close this out, and we can always re-open if we encounter any issues.
